#!/bin/sh

while read -r file
do
  case "$1" in
			"w")  xwallpaper --stretch "$file" && notify-send "Sxiv" "$file Wallpaper set!" ;;
			"u")  cp -rf "$file" ~/ && notify-send "Sxiv" "$file is copied to home!" ;;
    esac
done
